### DISCUSSION TITLE
Flood of null pointer exceptions (ISPN000136) reports for a period of time

### DISCUSSION THREAD

**Discussion by ajheres** [infinispan/infinispan-operator#2270] [Q&A]
In our setup with two clusters, both running an Infinispan server managed by the Infinispan operator, we are suffering from a flood of reports, like this:

> 09:35:44,959 ERROR (jgroups-17365,xsite,_distributed-grid-0-39162:AccB)
>   [org.infinispan.interceptors.impl.InvocationContextInterceptor]
>   ISPN000136: Error executing command IracPutKeyValueCommand on Cache 'track-local',
>   writing keys [WrappedByteArray[\0\0\0\0\3\e\e\0\-\0\0\0\0\-\4\0\0\0\-\8\0\e\c\-\9\c\2\5\6\8\5\d\0\2\0\0 (36 bytes)]] java.lang.NullPointerException

The reports contain a number of keys, but the errors for these keys are repeated many times (hundreds per second). This happens during a few minutes.

The cache is configured as replicated with backup:

```yaml
  clusterName: distributed-grid
  name: track-local
  template: |
    replicatedCache:
      backups:
        AccA:
          backup:
            strategy: "ASYNC"
              stateTransfer:
                chunkSize: "512"
                timeout: "2400000"
                maxRetries: "30"
                waitTime: "2000"
                mode: "AUTO"
      mode: "SYNC"
      statistics: "true"
      encoding:
        key:
          mediaType: "text/plain"
        value:
          mediaType: "application/octet-stream"
      expiration:
        lifespan: "-1"
        maxIdle: "1200000"
  updates:
    strategy: retain
```

The key/values in the store are continuously updated. +/- 1000 items in store.  +/- 50 updates/s. One side is writing. Writing bandwidth is +/- 1KB/s.
I have the impression that it has to do with the backup. Tried all kind of cache and server settings, but the errors keep coming with intervals.
Can anyone help me further to solve this problem?

Server version: 15.2.1.Final.
