### ISSUE TITLE
Detect that expose cluster or cross-site LoadBalancer type configured on unsupported platform

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1019]
Beginning Kubernetes 1.17 (OKD/OCP 4.4 and later) it's possible to determine is cloud provider supports `LoadBalancer` or not by the following finalizer presence on the Service
```
kind: Service
apiVersion: v1
metadata:
  name: example-infinispan-service
  namespace: infinispan-operator
.
.
.
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
```

We should detect and notify customers that `LoadBalancer` is not supported on the target platform instead of the generic error: `local x-site service host not yet available`. If platform supports `LoadBalancer` this should be not error, just notification

Namespace should be display while cross-site service lookup in addition to the `site service name`
https://github.com/infinispan/infinispan-operator/blob/f4d621a0fe007d22010d22b7268bf9b037af62ae/pkg/controller/infinispan/resources/config/xsite.go#L93-L98

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
