### ISSUE TITLE
Display all sites in CrossSiteViewFormed if only remote sites are specified in locations

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1026]
`CrossSiteViewFormed` conditions display not all sites if only remote locations are specified (it's enough for working cross-site but not enough for performing cross-site view around all sites).

```
service:
...
    sites:
      local:
        expose:
          type: NodePort
        name: xsite2
      locations:
      - clusterName: test-cross-site-view-kubernetes-xsite1
        name: xsite1
        namespace: namespace-for-testing-xsite1
        secretName: secret-xsite1
        url: kubernetes://172.18.0.2:6443
    type: DataGrid
status:
  conditions:
  - status: "True"
    type: PreliminaryChecksPassed
  - message: 'View: test-cross-site-view-kubernetes-xsite2-0-41320'
    status: "True"
    type: WellFormed
  - message: 'Cross-Site view: xsite1'
    status: "True"
    type: CrossSiteViewFormed
  podStatus:
    ready:
    - test-cross-site-view-kubernetes-xsite2-1
  statefulSetName: test-cross-site-view-kubernetes-xsite2
```
