### ISSUE TITLE
Unclear how to create  cache using CRD 

### ISSUE THREAD

**Issue by dicolasi** [infinispan/infinispan-operator#1040]
Hi all,
I am getting a bit confused on how to configure a cache using Json. Here what I created so far:

```
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: demand-cache
spec:
  clusterName: infinispan-cluster
  name: demand-cache
  template: |
    {
      "invalidation-cache": {
        "mode": "ASYNC",
        "locking": {
          "concurrency-level": 1000,
          "acquire-timeout": 15000,
          "striping": false
        },
        "memory": {
          "max-count":500,
          "when-full":"REMOVE"
        },
        "expiration": {
            "lifespan":5000,
            "max-idle":1000
        },
        "statistics": true
      }
    }
```

Is it correct?

**Comment by dmvolod** [comment]
Cache CR doesn't support JSON template
I would recommend to use Batch CR for more flexibility
Please have a look at the Batch CR example, but we don't have an actual cache JSON example
https://raw.githubusercontent.com/infinispan/infinispan-operator/master/deploy/cr/batch/batch-cm.yaml

**Comment by dicolasi** [comment]
Thanks @dmvolod I am a bit confused tbh. So let me explain the situation:
I have the following situation:

![Screenshot 2021-05-12 at 12 22 54](https://user-images.githubusercontent.com/54740533/117967331-d2154e80-b31c-11eb-9f3c-51dca19d4a53.png)

and I have created the following cache:

```
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: demand-cache
spec:
  clusterName: infinispan-datagrid-service
  name: demand-cache
  templateName: org.infinispan.DIST_SYNC
```
However I really do not see anything in the GUI:

![Screenshot 2021-05-12 at 12 27 06](https://user-images.githubusercontent.com/54740533/117967824-6ed7ec00-b31d-11eb-9210-81c92c730435.png)

If I run a local docker container `❯ docker run -it -p 11222:11222 -e USER="admin" -e PASS="password" quay.io/infinispan/server:12.1`  I can see this:

![Screenshot 2021-05-12 at 12 28 35](https://user-images.githubusercontent.com/54740533/117967985-9929a980-b31d-11eb-8851-5f8a5af1317e.png)

So, I have no idea why:
 - I do not see the demand-stats cache
 - I am not able to see anything in the GUI. I expect at least to add something manually as per local docker container.

**Comment by dmvolod** [comment]
Cache CR is available for the DataGrid Infinispan CR only. Please validate spec.service.type or change it (once create only)
https://infinispan.org/docs/infinispan-operator/master/operator.html#cache-cr
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan-datagrid-service
spec:
  replicas: 1
  service:
    type: DataGrid
```
If all requirements are met, please upload operator logs
