### ISSUE TITLE
Encryption type Service fails if only type provided

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1044]
Encryption secrets are not created on OCP 4.7.7 if only the encryption type "Service" is specified. However, this is the default behaviour on Openshift if no type is specified, in which case it works as expected when the `type` field is removed.

```yaml
spec:
  security:
    endpointEncryption:
      type: Service
```

So far only observed on the 2.0.x releases, needs to be verified on `master`.
