### ISSUE TITLE
Incorrect getting Ingress hostname value 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1057]
Value should be find in following Ingress structure
```
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
```
