### ISSUE TITLE
Regression of #634

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1071]
Issue #634 returned back due to regression and should be fixed again for `xsite` section
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    infinispan.yaml: |
      infinispan:
        clusterName: example-infinispan
        zeroCapacityNode: false
        locks: {}
      jgroups:
        transport: tcp
        dnsPing:
          query: example-infinispan-ping.default.svc.cluster.local
        diagnostics: false
      xsite:
        address: ""
        name: ""
        port: 0
        backups: []
      endpoints:
        auth: true
        dedicatedAdmin: true
  kind: ConfigMap
```
