### ISSUE TITLE
Cluster configuration ConfigMap updates on start 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#1102]
Seems to be this is regression of the #1007
Startup configuration ConfigMap
```
infinispan:
  authorization:
    enabled: false
    roleMapper: cluster
  clusterName: example-infinispan
  zeroCapacityNode: false
  locks: {}
jgroups:
  transport: tcp
  dnsPing:
    query: example-infinispan-ping.infinispan-operator.svc.cluster.local
  diagnostics: false
endpoints:
  auth: true
  dedicatedAdmin: true

```

`keystore` embedding later, that's wrong and forcing cluster rolling upgrade
```
infinispan:
  authorization:
    enabled: false
    roleMapper: cluster
  clusterName: example-infinispan
  zeroCapacityNode: false
  locks: {}
jgroups:
  transport: tcp
  dnsPing:
    query: example-infinispan-ping.infinispan-operator.svc.cluster.local
  diagnostics: false
keystore:
  path: /opt/infinispan/server/conf/keystore
  password: password
  alias: server
  crtPath: /etc/encrypt/keystore
endpoints:
  auth: true
  dedicatedAdmin: true
```

Probably this cause regression in cross-site forming also
