### ISSUE TITLE
Exposed port for LoadBalancer services (application and xsite) should be configurable

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#1169]

**Comment by ryanemerson** [comment]
To provide greater flexibility for xsite it should be possible for the local address:ip of the local site to be configured. Instead of exposing IP and address fields, we should allow users to specify an existing service and extra the information from here.

Something like:

```
sites:
  local:
    name: LON
    expose:
      type: LoadBalancer
      serviceName: someExistingServiceName
```

In order for the service to work as expected with xsite, it's necessary for the service selector to select pods with the labels `coordinator=true`.

**Comment by dmvolod** [comment]
It's better to do some work to be available Route or Ingress for cross site, as all service implementations are missing for internal communications and have a large number of limitations and security problems on all platforms.

**Comment by dmvolod** [comment]
> In order for the service to work as expected with xsite, it's necessary for the service selector to select pods with the labels `coordinator=true`

Also customer need to know other internals to be defined, it's better to be able customize a Port number, other features such as annotations already supported.

**Comment by ryanemerson** [comment]
> Also customer need to know other internals to be defined, it's better to be able customize a Port number

By internals do you mean the Infinispan ports for the service to target?

> other features such as annotations already supported

Can you elaborate? I'm not sure what you are referring to here

**Comment by dmvolod** [comment]
> By internals do you mean the Infinispan ports for the service to target?

Yes, target ports, correct label selectors which can be changed
We have all possible options, except `Port` only. I don't see any reason to customize  whole service which is very simple entity

**Comment by ryanemerson** [comment]
@dmvolod If we don't allow users to provide their own service, do you have a proposal in mind for the `.spec`?

**Comment by dmvolod** [comment]
Yes, @ryanemerson the proposals for HR and Cross-Site LoadBalancer specs are:
```
spec:
  replicas: 2
  expose:
    type: LoadBalancer
    port: 443
```

```
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        expose:
          type: LoadBalancer
          port: 443
```
