### ISSUE TITLE
Infinispan CR status content

### ISSUE THREAD

**Issue by sutaakar** [infinispan/infinispan-operator#1204]
Infinispan operator 2.0.6 provides information about configured security in its status:
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
...
  security:
    endpointEncryption:
      certSecretName: example-infinispan-cert-secret
      certServiceName: service.beta.openshift.io
      type: Service
    endpointSecretName: example-infinispan-generated-secret
...
status:
...
  security:
    endpointEncryption:
      certSecretName: example-infinispan-cert-secret
      certServiceName: service.beta.openshift.io
      type: Service
    endpointSecretName: example-infinispan-generated-secret
...
```

However Infinispan operator 2.1.4 doesn't provide security section in status, even when the security section is specified in spec. Is it expected behaviour?
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: kogito-infinispan
spec:
...
  security:
    endpointAuthentication: true
    endpointEncryption:
      certSecretName: kogito-infinispan-cert-secret
      certServiceName: service.beta.openshift.io
      type: Service
...
status:
  conditions:
    - status: 'True'
      type: PreliminaryChecksPassed
    - message: 'View: kogito-infinispan-0-7122'
      status: 'True'
      type: WellFormed
  podStatus:
    ready:
      - kogito-infinispan-1
  statefulSetName: kogito-infinispan
```
