### ISSUE TITLE
xsite with expose type LoadBalancer

### ISSUE THREAD

**Issue by andriipetruk** [infinispan/infinispan-operator#1247]
Hi, 
I want expose xsite as LoadBalancer with statc IP address. 
Please let me know how I can   set for service spec.loadBalancerIP ? or how I can set in config map xsite.address ?
Thanks!

**Comment by rigazilla** [comment]
> Hi,
> I want expose xsite as LoadBalancer with statc IP address.
> Please let me know how I can set for service spec.loadBalancerIP ? or how I can set in config map xsite.address ?
> Thanks!

Procedure to manually configure xsite should be described here:
https://infinispan.org/docs/infinispan-operator/2.1.x/operator.html#manual-xsite-views_cross-site

**Comment by andriipetruk** [comment]
Hi, @rigazilla thanks for replay. I read this manual and for me not clear how set my own IP for LB.
I have next config
---
  service:
    type: DataGrid
    sites:
      local:
        name: {{ .Values.region }}
        expose:
          type: LoadBalancer
      locations:
      {{- range $infinispanBackup }}
      - name: {{ .region }}
        url: infinispan+xsite://{{ .ip }}:7900
      {{- end }}
---

need some option for "local" part like we have for "location"  - url or option for LB static ip...

**Comment by fallen-up** [comment]
+1

**Comment by fallen-up** [comment]
so, i use:
```
resources:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: my-infinispan
      namespace: operators
    spec:
      channel: 2.3.x
      config:
        env:
        - name: MAKE_DATADIR_WRITABLE
          value: "true"
        - name: INFINISPAN_OPERATOR_TARGET_ANNOTATIONS
          value: |
            {"metallb.universe.tf/address-pool":"infinispan"}
      name: infinispan
      source: operatorhubio-catalog
      sourceNamespace: olm
```
```
but it works for both: xsite and datagrid.
workaround - use shared-ip
resources:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: my-infinispan
      namespace: operators
    spec:
      channel: 2.3.x
      config:
        env:
        - name: MAKE_DATADIR_WRITABLE
          value: "true"
        - name: INFINISPAN_OPERATOR_TARGET_ANNOTATIONS
          value: |
            {"metallb.universe.tf/address-pool":"infinispan",
            "metallb.universe.tf/allow-shared-ip":"true"}
      name: infinispan
      source: operatorhubio-catalog
      sourceNamespace: olm
```
what to do in case when you want use different ip?
