### ISSUE TITLE
Improve probe settings

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1387]
Current probes settings prevent Infinispan pod being available sooner than 10s. With a 10s periodCheck the readiness always happen in multiple of 10s. (If the server starts in 11s its marked as ready in 20s by k8s).

Given the pods are deployed sequentially on K8s StatefulSets after previous nodes are ready, this has a cumulative effect.  If a user deploys a cluster with replicas=3, and it takes 11s for a pod to be ready, the whole cluster won't be available for at least 1 minute even it could theoretically start up in 33s.

Current probe settings:

```
readinessProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 80
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
  
livenessProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
   initialDelaySeconds: 10
   timeoutSeconds: 80
   periodSeconds: 10
   successThreshold: 1
   failureThreshold: 5
   
startupProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
   initialDelaySeconds: 10
   timeoutSeconds: 80
   periodSeconds: 10
   successThreshold: 1
   failureThreshold: 60
  ```
  
  Proposal:
  
  ```
readinessProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
  initialDelaySeconds: 0
  timeoutSeconds: 80
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
  
livenessProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
   initialDelaySeconds: 0
   timeoutSeconds: 80
   periodSeconds: 10
   successThreshold: 1
   failureThreshold: 5
   
startupProbe: 
  httpGet: 
    path: rest/v2/cache-managers/default/health/status
    port: 11223
    scheme: HTTP
   initialDelaySeconds: 1
   timeoutSeconds: 80
   periodSeconds: 1
   successThreshold: 1
   failureThreshold: 600
  ```
