### ISSUE TITLE
No reconciliation after changing podTargetLabels

### ISSUE THREAD

**Issue by gkocur** [infinispan/infinispan-operator#1390]
My use case: I want to add labels to pods to inject istio sidecar containers.
According to the documentation I added to the Infinispan manifest:
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
  annotations:
    infinispan.org/podTargetLabels: "sidecar.istio.io/inject"
  labels:
    sidecar.istio.io/inject: "true"
```

But nothing happened. I had to remove the statefulset completely and the new one was created with proper `.spec.template.metadata.labels`.

I'd rather expect the change in statefulset and the rolling update.
