### ISSUE TITLE
Env vars in operator subscription

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-operator#1520]
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-infinispan
  namespace: namespace-for-testing
spec:
  channel: 2.2.x
  name: infinispan
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    env:
      - name: ADDITIONAL_VARS
        value: "[\"DEBUG\"]"
      - name: DEBUG
        value: true
```

each pod in the cluster's StatefulSet will have the DEBUG env variable set to true

This will apply to ALL Infinispan CRs created by this Operator.
