### ISSUE TITLE
FIPS compliance

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1666]
Currently it's only possible to disable FIPS mode on the Infinispan server JVMs by providing the following config:

```yaml
spec:
  container:
    extraJvmOpts: "-Dcom.redhat.fips=false"
    cliExtraJvmOpts: "-Dcom.redhat.fips=false"
    routerExtraJvmOpts: "-Dcom.redhat.fips=false"  
```

The operator should be able to detect that it's running on a FIPS enabled K8s cluster by executing `fips-mode-setup --is-enabled` or checking the `/proc/sys/crypto/fips_enabled` file. If enabled, the server should then be configured accordingly to allow FIPS compliance.

Known requirements:

TLS:
  - PEM files need to be converted to DER
  - Imported using NSSDB and `certuril`
  - `file-less` keystore configuration defined in the Infinispan security-realm
