### ISSUE TITLE
Operand Images should be loadable from environment variables

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1672]
In order to allow the Operator OLM bundle to be processed by various build systems that automatically generate image values, it should be possible for the `INFINISPAN_OPERAND_VERSIONS` json array to reference images by an environment variable denoted in the form `${ENV_NAME}`.

```yaml
- name: INFINISPAN_OPERAND_VERSIONS
  value: |-
    [{
      "upstream-version": "13.0.10",
      "image": "${RELATED_IMAGE_OPENJDK_13.0.10}"
    }]
 - name: RELATED_IMAGE_OPENJDK_13.0.10
   value: quay.io/infinispan/server:13.0.10.Final
```
