### ISSUE TITLE
Default Anti-affinity strategy configuration with the Operator is not valid

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1707]
The default anti-affinity configuration contains a typo that can allow multiple Infinispan pods to be deployed on the same k8s host:

```yaml
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: datagrid-des
                infinispan_cr: datagrid-des
            topologyKey: r.kubernetes.io/hostname # Need to remove 'r.' prefix.
```
