### ISSUE TITLE
 Allow users to define credential-store entries

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1730]
In order to allow users to securely define custom server configurations requiring credentials, e.g. LDAP configurations, it's necessary for us to provide a way for users to define entries in the default credential-store.

We can optionally allow the user to specify a Secret containing the required credential-store references:

```yaml
spec:
  security:
    credentialStoreSecretName: user-secret
```
