### ISSUE TITLE
Config listener pod should have configurable log level

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1732]
Currently the default log level is Debug which is overly verbose for long term production use. We should set the default logging behaviour to be info and allow the user to configure this explicitly via the Infinispan CR spec as follows:

```yaml
spec:
  configListener:
    enabled: true
    logging: info|debug|error
```
