### ISSUE TITLE
Persistent cache delete workflow

### ISSUE THREAD

**Issue by jasaltvik** [infinispan/infinispan-operator#1793]
Hi again,

I am testing the process of recreating a persistent cache because of a change in the underlying cache template, but I don't really see how this can be done in a simple way.

Let's say you have a cache template like this (deployed as part of your custom `ConfigMap`)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
   name: infinispan-config
   namespace: datagrid
data:
  infinispan-config.yaml: >
    infinispan:
      cacheContainer:
        caches:
          mycachetemplate:
            distributedCacheConfiguration:
              mode: "SYNC"
              persistence:
                file-store:
              encoding:
                mediaType: "application/x-protostream"
```
Note that the `Infinispan` CR also has `spec.service.container.storage` and `spec.service.container.storageClassName` set up.

Let's say you have the corresponding `Cache` CR that use the cache template

```yaml
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: mycache
spec:
  clusterName: infinispan
  name: mycache
  templateName: mycachetemplate
```

Now let's say you discover that the encoding should be changed in the template so you update it, and the Infinispan Operator updates it just fine. Now I want to recreate the cache using the new template, so I delete the `Cache` CR. I expect the cache to disappear from Infinispan, but it's still there on disk (I assume this is because of the persistence configuration). If I redeploy the `Cache` CR it will just continue to use the old cache with the old cache template. Do I actually have to clean it from disk to be able to recreate it with the new template? What is the expected workflow in these types of situations? I also tried the `Cache` CR `spec.updates.strategy: recreate` option, but this doesn't seem to have any effect.

**Comment by ryanemerson** [comment]
@jasaltvik When you update the ConfigMap does the cluster redeploy all of the pods?

I suspect that the template hasn't been updated as expected on the server itself. You can check this by making a [REST call against the Infinispan pods](https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_cache_manager_cache_templates)

**Comment by jasaltvik** [comment]
> @jasaltvik When you update the ConfigMap does the cluster redeploy all of the pods?
> 
> I suspect that the template hasn't been updated as expected on the server itself. You can check this by making a [REST call against the Infinispan pods](https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_cache_manager_cache_templates)

Hi @ryanemerson. Thanks for getting back to me. An update of the `ConfigMap` redeploys the Infinispan pods. I havent' ran the REST call directly, but I see that it is called via the console (via `<url>/console/container/default/configurations/`), and I see the updated template there. Something that surprised me was that I deleted the `Cache` CR, and then the config listener actually recreated it like this at some point (updated names and template based on the example I used)

```yaml
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  generateName: mycache-
  annotations:
    infinispan.org/listener-generation: '1'
  name: mycache-9zx8g
spec:
  clusterName: infinispan
  name: mycache
  template: |
    distributedCache: 
      owners: "2"
      mode: "SYNC"
      encoding: 
        key: 
          mediaType: "application/x-protostream"
        value: 
          mediaType: "application/x-protostream"
      persistence: 
        fileStore: ~
  updates:
    strategy: retain
```

Note that the encoding has already been updated in the template, but it's still redeploying it using the old template. Can you explain why the config listener automatically recreates it in this way? The reason I noticed that the config listener had done it was because I was attempting to create it myself, but wasn't allowed as it already existed. Do I need to use `updates.strategy: recreate` on all caches from the start to have better control?

**Comment by ryanemerson** [comment]
@jasaltvik Thanks for the additional information.


> Now let's say you discover that the encoding should be changed in the template so you update it, and the Infinispan Operator updates it just fine. Now I want to recreate the cache using the new template, so I delete the `Cache` CR. I expect the cache to disappear from Infinispan, but it's still there on disk (I assume this is because of the persistence configuration). If I redeploy the `Cache` CR it will just continue to use the old cache with the old cache template. Do I actually have to clean it from disk to be able to recreate it with the new template? What is the expected workflow in these types of situations?

I think you've found a gap in our offering. Defining a cache/configuration on the server ConfigMap makes it trickier for the Operator to manage it's lifecycle and in this case you're right that the old file-store data will remain. I'll have a think about we can better handle this, but for now I think the only workaround is for you to also update the file-store path when changing the cache configuration. That way the old file-store will be ignored on cluster restart. If the old file-store(s) are large, you can manually exec into the pods to delete them.

**Comment by jasaltvik** [comment]
@ryanemerson Thanks for the explanation and input.

> Defining a cache/configuration on the server ConfigMap makes it trickier for the Operator to manage it's lifecycle and in this case you're right that the old file-store data will remain.

By this you mean the cache template? The reason for adding it in the server configuration is to avoid bloated `Cache` CRs so that the teams only need to specify a template for their products which will automatically map it to the correct role in the multi-tenancy setup.

> I'll have a think about we can better handle this, but for now I think the only workaround is for you to also update the file-store path when changing the cache configuration. That way the old file-store will be ignored on cluster restart. If the old file-store(s) are large, you can manually exec into the pods to delete them.

Thanks. I'll have a look at how we potentially can use separate paths if we need to update the cache configuration. I guess this must be part of the cache template update procedure if we want to avoid having to recreate the cluster from scratch for every template update to ensure the right templates are used.

> With regards to the Cache CRs that reference the "mycachetemplate" configuration, I recommend that you don't delete these manually.

This is a bit tricky since the `Cache` CRs are part of the application GitOps deployment, and sometimes the developers will wipe an app to set it up from scratch. I guess this should be fine as long as the `Cache` CRs are redeployed instantly (which is the normal use-case). It doesn't make sense to move these to the admin (platform team) setup as then we would be bottlenecks for something that the devs should be able to control. We basically only care about the multi-tenancy setup and general data grid operations.

> On cluster restart (after the ConfigMap update), the original CR(s) will be reconciled against the new cluster and the cache should be recreated.

I guess I don't understand the "recreated" part of this, as it seems the Infinispan pods will just continue to use the same path as before (with whatever content that existed before the restart). Or are you thinking about the scenario where the file path has been updated, and that the caches will be recreated on the new path? If this is the case I understand what you mean.

And one final question. Would updating the `Cache` CRs from `spec.updates.strategy: retain` to `spec.updates.strategy: recreate` help with anything in this particular setup? Do you think `spec.updates.strategy: recreate` is a better fit here?

**Comment by jasaltvik** [comment]
@ryanemerson Thanks for the input!

> That's a very valid use-case and makes sense. The bit the Operator is missing is a "CacheConfiguration" CR #748 that would allow you to use this same approach in a k8s native way, allowing the Operator to better handle the lifecycle/cleanup of the various resources on update. I believe you have a Data Grid subscription. Raising this issue as a customer case will greatly improve the chances of thing being prioritised, I recommend you do this slightly_smiling_face.

Thanks, I'll look into this.

> None taken slightly_smiling_face. Why did you originally want persistence? I ask, because there's a non-negligible performance cost to adding it and it sounds like you're also able to remove it, so maybe there's a better pattern we can use for your needs.

Adding persistence just seemed like a natural thing to do when going into the rabbit hole of setting up a centralized multi-tenancy setup, and looking into the parts about the setup that wasn't handled earlier. I have started some internal discussion regarding persistence, and it looks while we'll continue without it. 

> If I understand correctly, on update of a cache template on the server the Cache CRs will remain the same anyway as they only reference said template by name, so I don't think your GitOps syncer will need to remove the existing CRs.

Yeah, agreed. It was only removed as I thought it was the only way to be able to recreate the cache with the updated template. I guess this should work when persistence is deactivated. One final question regarding this: if we decide to remove persistence, does that mean that I actually should remove both parts of it (ref: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.4/html/data_grid_operator_guide/creating-services#persistent-volume-claims_services). This means removing both `spec.service.container.storage+storageClassName` (`Infinispan` CR) and `<file-store/>` (Cache templates). Would I also need to pair this with `spec.updates.strategy: recreate` on the `Cache` CRs, or should it be fine keeping the `retain` config now that persistence is off? I saw you mentioned that recreate would be appropriate for the GitOps approach, but I was a bit confused if this was also valid if persistence was turned off?

Thanks for all the help and input with this!

**Comment by ryanemerson** [comment]
The PVCs used by a Cluster's StatefulSet, i.e. what's configured with `spec.service.container.storage+storageClassName`, are used to store globalstate about a cluster which is used on pod/infinispan cluster restarts. This is required to reason about expected cluster topologies, amongst other things, to prevent data loss and ensure [availability strategies](https://infinispan.org/docs/stable/titles/configuring/configuring.html#partition-handling) are respected. These PVCs are also to ensure any configuration added at runtime survives restarts, although that's probably not applicable in your case.

So even if you don't require persistence at the cache level with a file-store, it still makes sense to have `!ephemeralStorage` defined. The default behaviour of the Infinispan CR is to configure:

```yaml
spec:
   service:
     container:
       storage: 1Gi
       ephemeralStorage: false
```
This should be more than enough storage for the global state I mentioned previously. `.storageClassName` is optional and the cluster default will be used if you don't explicitly configure this.



> Would I also need to pair this with `spec.updates.strategy: recreate` on the `Cache` CRs, or should it be fine keeping the `retain` config now that persistence is off?

`recreate` is the way to go for GitOps as it ensures that a config update will always be applied on the cluster. `retain` only updates a cache configuration if the change can be applied at runtime without having to drop the cache and start again. This applies to any config change, not just persistence specific.
