### ISSUE TITLE
Option to define multiple rack configuration

### ISSUE THREAD

**Issue by andrey-dubnik** [infinispan/infinispan-operator#1801]
Hi,

Maybe a newbie question and there is already a perfect way to configure a rack aware topology...

Currently I can't see a way to specify rack topology for the cluster node deployment meaning that even for the multiple data copies there is a risk of the data copy placement into the nodes within the same availability zone (AZ). Affinity block can make sure nodes are distributed across the zones but there is no zonal topology awareness other than the node.name and the cluster.name. 

It would be great if Infinispan operator allowed for the Rack grouping of nodes. The use case for it would be running the nodes across different failure domains within the same cluster so the data is guaranteed to be replicated into a different availability zone. 

Example on how this is implemented in k8ssandra operator where k8s labels are associated with the racks. This configuration results in the nodes provisioned with the rack attributes configured and required node affinity block (generated for the actual deployment) makes sure the PODs scheduled for the rack configuration are only placed into the nodes with the corresponding labels.

```yaml
      apiVersion: k8ssandra.io/v1alpha1
      kind: K8ssandraCluster
      ...
      spec:
        cassandra:
              ...
              racks:
              - name: az-1
                nodeAffinityLabels:
                  cassandra-rack: az1
              - name: az-2
                nodeAffinityLabels:
                  cassandra-rack: az2
              - name: az-3
                nodeAffinityLabels:
                  cassandra-rack: az3
```

**Comment by ryanemerson** [comment]
@andrey-dubnik How many Infinispan replicas do you want to reside in each availability zone? If a single replica is sufficient, then it should be possible to use the anti-affinity configuration to achieve this:

```yaml
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: infinispan-pod
            clusterName: <cluster_name>
            infinispan_cr: <cluster_name>
        topologyKey: "topology.kubernetes.io/zone"
```
https://infinispan.org/docs/infinispan-operator/main/operator.html#anti-affinity-strategies_availability

For multiple replicas in each of the availability zones, you could replicate the rack aware topology you describe by having multiple Infinispan clusters. Each cluster would have it's affinity settings configured so that scheduled pods reside in their given AZ, and it's site backups are the clusters in the other AZs.
