### ISSUE TITLE
Tolerations not supported

### ISSUE THREAD

**Issue by svenhakvoort** [infinispan/infinispan-operator#1803]
Hi, are there any plans to support providing tolerations in addition to nodeAffinity?

Thank you!

**Comment by ryanemerson** [comment]
Hi @svenhakvoort, it's certainly something we can look into adding.

We also plan to add support for other configurations from the pod spec, such as [TopologyPodConstraints](https://github.com/infinispan/infinispan-operator/issues/1801#issuecomment-1486940366), so it would be good if we established a convention for configuring Pod spec components. Currently we allow pod affinity to be configured via `spec.affinity`, so the question is do we continue to allow top level configuration in a similar manner or nest these fields under an element.

For example, top level:

```yaml
kind: Infinispan
...
spec:
  affinity:
    ...
  tolerations:
    ...
  topologySpreadConstraints:
    ...
```

Or nested:

```yaml
kind: Infinispan
...
spec:
  statefulset:
    affinity:
      ...
    tolerations:
      ...
    topologySpreadConstraints:
      ...
```

IMO the latter is the more flexible approach going forward, however we will need to transform the existing `spec.affinity` field if specified.

@rigazilla WDYT?

**Comment by svenhakvoort** [comment]
Hi @ryanemerson thank you for your reply.

I definitely agree with the second approach being the most flexible since it allows for more specific pod specs on different components if needed. And going from `spec.affinity` to `spec.statefulset.affinity` is very minor and to us at least would be no concern at all.

**Comment by rigazilla** [comment]
> 
> IMO the latter is the more flexible approach going forward, however we will need to transform the existing `spec.affinity` field if specified.
> 
> @rigazilla WDYT?

yeah, imo better to go with a nested struct

**Comment by ryanemerson** [comment]
This configuration will be added under the `spec.scheduling` element the same as the `affinity` and `priorityClassName` fields, e.g.:

```yaml
kind: Infinispan
...
spec:
  scheduling:
    affinity:
      ...
    tolerations:
      ...
    topologySpreadConstraints:
      ...
```
