### ISSUE TITLE
Topologyspread configuration

### ISSUE THREAD

**Issue by tolleiv** [infinispan/infinispan-operator#1844]
Using infinispan-operator 2.3.3 provides Pods with a Pod-Anti-Affinity configuration to split them to different hosts, this is a good default.

With topology-spread-constraints this can be done in a more relyable way (see https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#comparison-with-podaffinity-podantiaffinity ).
 > podAntiAffinity:
repels Pods. If you set this to requiredDuringSchedulingIgnoredDuringExecution mode then only a single Pod can be scheduled into a single topology domain; if you choose preferredDuringSchedulingIgnoredDuringExecution then you lose the ability to enforce the constraint.

It would be great if the InfinitySpan CR would allow to also allow to define `topologySpreadConstraints`.

**Comment by ryanemerson** [comment]
Thanks for creating the issue @tolleiv. This is an area we're continuing to evolve and we plan to add this in the future.

I have just merged a PR https://github.com/infinispan/infinispan-operator/pull/1851 that allows a pod's priortyClass to be configured via `spec.scheduling`, so the intention would be to build upon this work and provide the following API:

```yaml
spec:
  scheduling:
      # Configure a topology spread constraint
    topologySpreadConstraints:
      - maxSkew: <integer>
        minDomains: <integer> # optional; beta since v1.25
        topologyKey: <string>
        whenUnsatisfiable: <string>
        labelSelector: <object>
        matchLabelKeys: <list> # optional; beta since v1.27
        nodeAffinityPolicy: [Honor|Ignore] # optional; beta since v1.26
        nodeTaintsPolicy: [Honor|Ignore] # optional; beta since v1.26
```
