### ISSUE TITLE
Infinispan webhook should prevent incompatible TLS configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1848]
It's currently possible for a user to create a Infinispan CR as follows:

```yaml
spec
  security:
    endpointEncryption:
      certSecretName: infinispan-test-cert-secret
      certServiceName: service.beta.openshift.io
      type: Secret
```

Even though the `certServiceName` and `type=Secret` are incompatible. We should prevent such CRs being created.
