### ISSUE TITLE
Allow StatefulSet PriorityClass to be configured

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1850]
It should be possible for a user to configure the `PriorityClassName` used by the cluster StatefulSet via the Infinispan CR:

```yaml
kind: Infinispan
...
spec: 
  statefulset: 
    affinity: 
      ...
    priorityClassName: ""
    # Possible future configurations
    tolerations: 
      ...
    topologySpreadConstraints: 
      ...
```

Utilising a nested `spec.statefulset` structure provides increased flexibility that we can leverage for future enhancements such as https://github.com/infinispan/infinispan-operator/issues/1801 and https://github.com/infinispan/infinispan-operator/issues/1803

**Comment by Crumby** [comment]
@ryanemerson Wouldn't it be better to go with something like `qos`, `schuduling`  or `schedulingRules` instead of `statefulset` (btw. it should be `statefulSet` for consistency). The latter sounds way to generic as basically anything could fit in there including bunch of stuff we already have defined elsewhere and in the same time it won't allow for full SS configuration (as it shouldn't).

**Comment by ryanemerson** [comment]
Very good points. I like `scheduling`, so it would be:

```yaml
spec: 
  scheduling: 
    affinity: 
      ...
    priorityClassName: ""
    # Possible future configurations
    tolerations: 
      ...
    topologySpreadConstraints: 
      ...
```
