### ISSUE TITLE
linkerd labels are not propagated to infinispan pods

### ISSUE THREAD

**Issue by cgmEdi** [infinispan/infinispan-operator#1968]
In our k8s cluster we use the infinispan operator in version 2.3.6.Final (image: quay.io/infinispan/operator:2.3.6.Final).
With an infinispan in version 14.0.21.Final
```yaml
        - name: INFINISPAN_OPERAND_VERSIONS
          value: |-
            [
              {
                "upstream-version": "13.0.8",
                "image": "quay.io/infinispan/server:13.0.8.Final"
              },
              {
                "upstream-version": "14.0.21",
                "image": "quay.io/infinispan/server:14.0.21.Final"
              }
            ]
```

We are trying to get the created infinispan pods meshed with an linkerd service mesh. When the pods are created and send to the linkerd admission webhook, the proxies sidecars get injected, as well as all the linkerd annotations but for some reason the labels that linkerd patches in, get ignored and the pods are left without those.

Example:

Source infinispan.yaml:
```yaml
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    infinispan.org/podTargetLabels: kyverno.cgm.com/skip-policies
    infinispan.org/targetLabels: kyverno.cgm.com/skip-policies
  labels:
    kyverno.cgm.com/skip-policies: "true"
  name: infinispan-managed-idm
  namespace: team-idm
spec:
  replicas: 3
  service:
    type: DataGrid
  version: 14.0.21
```

Actually deployed pods:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 3c48c9126ce26d170ec9614ff8e59115cfcc2b03d95b6d1c3688a81921eb557b
    cni.projectcalico.org/podIP: 10.100.249.100/32
    cni.projectcalico.org/podIPs: 10.100.249.100/32
    config.linkerd.io/opaque-ports: '11222,11223'
    jaeger.linkerd.io/tracing-enabled: 'true'
    kubectl.kubernetes.io/restartedAt: '2024-01-09T10:21:42Z'
    linkerd.io/created-by: linkerd/proxy-injector stable-2.14.6
    linkerd.io/inject: enabled
    linkerd.io/proxy-version: stable-2.14.6
    linkerd.io/trust-root-sha256: 82f2f601d1408da362165ce1e48a1c69ac742362d7a5fed4230c74011ea734ab
    updateDate: '2024-01-09 10:15:02.14630544 +0000 UTC m=+24984.519383028'
    viz.linkerd.io/tap-enabled: 'true'
  creationTimestamp: '2024-01-09T10:22:47Z'
  generateName: infinispan-managed-idm-
  labels:
    app: infinispan-pod
    app.kubernetes.io/created-by: infinispan-managed-idm
    clusterName: infinispan-managed-idm
    controller-revision-hash: infinispan-managed-idm-fbff44984
    infinispan_cr: infinispan-managed-idm
    kyverno.cgm.com/skip-policies: 'true'
    statefulset.kubernetes.io/pod-name: infinispan-managed-idm-0
```

Expected Pods:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 3c48c9126ce26d170ec9614ff8e59115cfcc2b03d95b6d1c3688a81921eb557b
    cni.projectcalico.org/podIP: 10.100.249.100/32
    cni.projectcalico.org/podIPs: 10.100.249.100/32
    config.linkerd.io/opaque-ports: '11222,11223'
    jaeger.linkerd.io/tracing-enabled: 'true'
    kubectl.kubernetes.io/restartedAt: '2024-01-09T10:21:42Z'
    linkerd.io/created-by: linkerd/proxy-injector stable-2.14.6
    linkerd.io/inject: enabled
    linkerd.io/proxy-version: stable-2.14.6
    linkerd.io/trust-root-sha256: 82f2f601d1408da362165ce1e48a1c69ac742362d7a5fed4230c74011ea734ab
    updateDate: '2024-01-09 10:15:02.14630544 +0000 UTC m=+24984.519383028'
    viz.linkerd.io/tap-enabled: 'true'
  creationTimestamp: '2024-01-09T10:22:47Z'
  generateName: infinispan-managed-idm-
  labels:
    app: infinispan-pod
    app.kubernetes.io/created-by: infinispan-managed-idm
    clusterName: infinispan-managed-idm
    controller-revision-hash: infinispan-managed-idm-fbff44984
    infinispan_cr: infinispan-managed-idm
    kyverno.cgm.com/skip-policies: 'true'
    statefulset.kubernetes.io/pod-name: infinispan-managed-idm-0
    **linkerd.io/control-plane-ns: cluster-base-service-mesh-linkerd
    linkerd.io/proxy-statefulset: infinispan-managed-idm
    linkerd.io/workload-ns: team-idm**
```

For resources, that are not managed by the infinispan operator, the injection of labels works fine.
