### ISSUE TITLE
Specify TZ environment variable in POSIX format

### ISSUE THREAD

**Issue by theashiot** [infinispan/infinispan-operator#1977]
The expression("Asia/Tokyo") does not affect the local timezone in [1]. It needs to be specified in Posix format like "JST-9".
Sample:

```
kind: Subscription
spec:
  ...
  config:
    env:
    - name: ADDITIONAL_VARS
      value: "[\"TZ\"]"
    - name: TZ
      value: "JST-9"

```

[1] https://infinispan.org/docs/infinispan-operator/main/operator.html#defining-environment-variables_services
