### ISSUE TITLE
Annotations in CRD to be inherit by the pods

### ISSUE THREAD

**Issue by santinoncs** [infinispan/infinispan-operator#2048]
Is it possible to have the following feature?
I'd like to be able to set an specific annotation to the pods created by the CRD and the operator

Either add this annotations in the CR

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    example.io/keycloak: test
  labels:
    app.kubernetes.io/managed-by: Helm
   ...
...
```

So this annotation
```
    example.io/keycloak: test
```
is passed to the pod

Or maybe we can add an annotation to the CRD

```

...
	Autoscale *Autoscale `json:"autoscale,omitempty"`
	// +optional
	Annotations map[string]string `json:"annotations,omitempty"`
...
```
