### ISSUE TITLE
Pod cpu/memory limits have to be set

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#205]
We're currently only adding resource requests, but more importantly limits have to be set to!

```
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
```
