### ISSUE TITLE
Include Operand deprecation status in Infinispan CR .status

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#2084]
The Infinispan CR status object displays information about the reconciled operand, we should include an additional field to show whether said operand is deprecated or not, e.g.:

```
status:
  operand:
    version: 13.0.10
    deprecated: true
```
