### ISSUE TITLE
Add support for IP/CIDR whitelisting of the incoming traffic

### ISSUE THREAD

**Issue by andrey-dubnik** [infinispan/infinispan-operator#2139]
Hi,

As an endpoint can be exposed towards the internet it is nice to be able to limit the access to a set of IPs and CIDRs. There are few expose types within ISPN operator configuration and hopefully all support IP whitelisting.

e.g. for the LoadBalancer It could be done by adding `loadBalancerSourceRanges` to the External Service definition (works in EKS, [AKS](https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#restrict-inbound-traffic-to-specific-ip-ranges), GCP and likely OC.

It used to be an easier option of using the annotation `service.beta.kubernetes.io/load-balancer-source-ranges` but it seem to be [deprecated now](https://kubernetes.io/docs/reference/labels-annotations-taints/#service-beta-kubernetes-io-load-balancer-source-ranges) and a recommendation is to use the spec.loadBalancerSourceRanges on the Service resource instead.

Does it makes sense to add feature like this?

Thanks,
Andrey

**Comment by ryanemerson** [comment]
I think that makes sense, we could expose this configuration as follows:

```yaml
spec:
  expose:
    type: LoadBalancer
    port: 65535
    loadBalancerSourceRanges:
      - 0.0.0.0/0
```

We would then throw an error on the validating webhook if this element is specified with type=NodePort|Route

**Comment by ryanemerson** [comment]
Actually, a more generic solution such as the following would be more flexible. We can then configure the different expose types appropriately if supported (I haven't looked into the implementation details yet):

```yaml
spec:
  expose:
    type: LoadBalancer
    port: 65535
    sourceRanges:
      - 0.0.0.0/0
```
