### ISSUE TITLE
Infinispan and Data Grid operators define the same kind, name and version

### ISSUE THREAD

**Issue by ricardozanini** [infinispan/infinispan-operator#226]
Hi!

We're using Infinispan Operator as a dependency for our own operator and sometimes OLM installs DataGrid instead of Infinispan. This is happening because both define the same kind, name and version:

```yaml
    required:
    - description: Represents a Infinispan cluster used internally by Kogito Data
        Index Service
      displayName: Infinispan Cluster
      kind: Infinispan
      name: infinispans.infinispan.org
      version: v1
```
Is it possible to have different kind for DataGrid? That way we can differentiate from the upstream/downstream projects.

Many thanks!
