### ISSUE TITLE
WellFormed not reach even if view correctly set

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#241]
Sometimes `wellFormed` returns false even if view has been correctly set:

```
    conditions:
    - message: 'Views: example-infinispan-0-62976,example-infinispan-1-56788,example-infinispan-2-26699'
      status: "False"
      type: wellFormed
```

Could this be due to a merge?
