### ISSUE TITLE
No need for ReplicasWantedAtRestart

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#247]
Even if you change replicas to 0, Infinispan resource contains information about last applied configuration. That could be used to figure what the number of replicas are required to restart:

```
- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"infinispan.org/v1","kind":"Infinispan","metadata":{"annotations":{},"name":"example-infinispan","namespace":"infinispan-testing"},"spec":{"replicas":1}}
```
