### ISSUE TITLE
Discussion: Move cluster and cache names to the meta section

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#403]
@rigazilla what do you think about to move cluster and cache (a little bit confusing with two records in meta and spec section) names to the meta section
The CRD yaml sample will look like

```
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: mycache
  labels:
    infinispan.org/cluster: example-infinispan
spec:
  adminAuth:
    secretName: basic-auth
  templateName: org.infinispan.DIST_SYNC
```
