### ISSUE TITLE
Infinispan instance stuck during project termination

### ISSUE THREAD

**Issue by sutaakar** [infinispan/infinispan-operator#412]
If you delete a project containing running Infinispan instance (not the operator itself but an instance created by operator) then project deletion will get stuck and hanging.
The problem seems to be related to Infinispan finalizer.

Workaround is to delete finalizer `finalizer.infinispan.org` from Infinispan CR.

Reproduced in environment:
Infinispan operator 1.1.2
OCP 4.4.5
OpenStack (reproduced on AWS too)

Steps to reproduce:
- Install Infinispan operator
- Create new Infinispan instance using CR:
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 1
```
- Wait until the instance starts
- Delete whole project
=>
Project will get stuck in deleting phase.
