### ISSUE TITLE
Make connector credentials configurable by the user

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#44]
User must be able to specify username/password credential needed for authentication to the connector.
User must create k8s secret with credentials:
```
apiVersion: v1
kind: Secret
metadata:
  name: connector-secret
type: Opaque
stringData:
  connector-username: connectorusr
  connector-password: connectorpass
```
and refer it in the object creation yaml as:
```
spec:
  connector:
    secret:
      type: Credentials
      secretName: connector-secret
```
