### ISSUE TITLE
[help/question] The cache is not created by the operator 

### ISSUE THREAD

**Issue by bordeuax** [infinispan/infinispan-operator#444]
Using infinispan operator i can't create caches into infinispan cluster(no any log on operator side).
* infinispan status cluster 
```
Status:
  Conditions:
    Message:  View: test-datagrid-0-41892
    Status:   True
    Type:     wellFormed
```

* Operator version : jboss/infinispan-operator:1.1.2.Final 
* K8S infinispan definition 

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: test-datagrid
spec:
  image: infinispan/server:10.1.8.Final
  replicas: 1
  service:
    type: DataGrid
    container:
      storage: 2Gi
  security:
    endpointSecretName: test-datagrid-secret
  container:
    extraJvmOpts: ""
    cpu: "1000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: trace
      org.jgroups: debug
  expose:
    type: ClusterIP
```

* K8S cache definition 

```
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: test-cache
spec:
  adminAuth:
    secretName: test-basic-auth
  clusterName: test-datagrid
  name: test-cache
  templateName: org.infinispan.DIST_SYNC
```

**Comment by dmvolod** [comment]
@bordeuax operator 1.x doesn't support Cache CR. It's only implemented in master and targeted for 2.0.0

**Comment by bordeuax** [comment]
@dmvolod , thanks for your reactivity. But any way

**Comment by rigazilla** [comment]
@bordeuax there's a nightly image build for master here:
`docker pull jboss/infinispan-operator:latest`

PS
you don't need
```
  expose:
    type: ClusterIP
```
a clusterIP service is created by default. `expose` is for external exposition: NodePort, LoadBalancer,Route(2.x release only)

**Comment by bordeuax** [comment]
@dmvolod , @rigazilla  thanks a lot for your feedback. From your suggestion i done 3 tests: 
* Create cache dynamically from code 
* using `latest` version of operator 
* using `2.0.0.Alpha1` version of operator 
In all cases i have the same error : 
`ISPN004005: Error received from the server: java.lang.SecurityException: ISPN006017: Unauthorized 'PUT' operation  `
Definition for test-basic-auth secret :
```
apiVersion: v1
stringData:
  username: developer
  password: devpassword
kind: Secret
metadata:
  name: test-basic-auth
type: Opaque
```

**Comment by tristantarrant** [comment]
Are you configuring the client for authentication _

**Comment by bordeuax** [comment]
Normally yes (i verified several times). I also tested with both users `developer` and `operator`

**Comment by rigazilla** [comment]
@bordeuax please check your conf.
If you're using the infinispan CR at the top, you should have a secret named `test-datagrid-secret` with content similar to:
```
apiVersion: v1
kind: Secret
metadata:
  name: test-datagrid-secret
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: developer
      password: changeme
    - username: operator
      password: changemetoo
```
