### ISSUE TITLE
Sites structure displays an empty value if it not defined

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#448]
```
spec:
  container:
    cpu: 1000m
    memory: 1Gi
  image: infinispan/server:10.1.8.Final
  logging:
    categories:
      org.infinispan: trace
      org.jgroups: debug
  replicas: 1
  security:
    endpointEncryption:
      certSecretName: test-datagrid-cert-secret
      certServiceName: service.beta.openshift.io
      type: service
    endpointSecretName: test-datagrid-secret
  service:
    container:
      storage: 1Gi
    sites:
      local:
        expose: {}
        name: ""
    type: DataGrid
status:
```

Config also set with xsite empties 
```
data:
  infinispan.yaml: |
    clusterName: test-datagrid
    jgroups:
      transport: tcp
      dnsPing:
        query: test-datagrid-ping.ispn-test.svc.cluster.local
      diagnostics: false
    keystore:
      path: /opt/infinispan/server/conf/keystore
      password: password
      alias: server
      crtPath: /etc/encrypt
    xsite:
      address: ""
      name: ""
      port: 0
      backups: []
    logging:
      categories:
        org.infinispan: trace
        org.jgroups: debug
```
