### ISSUE TITLE
Align Status.Conditions.Type and Status with the k8s commons

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#482]
It would be nice to follow by k8s rules and done following changes:
* Add enums for all types to prevent error in code and avoid strings for this
* All types must match UppperCamelCase naming template, i.e.
```
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-07-23T15:07:23Z'
      lastTransitionTime: '2020-07-23T15:07:23Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
```

Also _status_ should use enums. Message should be optional
