### ISSUE TITLE
Worker label selector for getting NodePort host/port does not return any nodes

### ISSUE THREAD

**Issue by donovanmuller** [infinispan/infinispan-operator#523]
When configuring cross site replication and using a `NodePort` expose type on a Kubernetes cluster:

```yaml
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
spec:
  replicas: 2
  security:
    endpointSecretName: xxx
  service:
    type: DataGrid
    expose:
      type: NodePort 
    sites:
      local:
        name: xxx 
        expose:
          type: NodePort 
...
```

the label selector for worker nodes does not return any nodes with the current empty label value on a RKE Kubernetes 1.15.11 cluster, despite their being ready worker nodes.  https://github.com/infinispan/infinispan-operator/blob/21d35fe983b504649dd773c23e74af9abac37696/pkg/controller/utils/infinispan/configuration/xsite.go#L173
