### ISSUE TITLE
Incorrect keystore being loaded when deploying on OpenShift

### ISSUE THREAD

**Issue by noelo** [infinispan/infinispan-operator#553]
I've using infinspan operator 2.0.3 on OCP 4.5.7 to create a cache instance with the following config
```yaml
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: tournamentcache
spec:
  replicas: 1
  security:
    endpointSecretName: tournament-cache-authsecret
  service:
    type: Cache
```

However when I try and connect I keep getting the wrong SSL certificate. I'd expect to receive a cert based on the openshift-service-serving-signer CA e.g.

```yaml
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 7669761631813819337 (0x6a707791682edbc9)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-service-serving-signer@1597915285
        Validity
            Not Before: Aug 31 19:49:36 2020 GMT
            Not After : Aug 31 19:49:37 2022 GMT
        Subject: CN=tournamentcache.petbattle.svc
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
```

But the one I receive in the SSL challenge is this one
```yaml
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 9519305399427893637 (0x841b5dd3495b8985)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=localhost
        Validity
            Not Before: Aug 31 19:49:49 2020 GMT
            Not After : Aug 29 19:49:49 2030 GMT
        Subject: CN=localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
```

I think I know what's causing it but I'm not 100%.
So I've checked the running pod and there are two keystores being added to the infinispan conf directory

```bash
sh-4.4$ ls -la /opt/infinispan/server/conf/key*
-rw-rw-r--. 1 185 root 2383 Aug 31 19:49 /opt/infinispan/server/conf/keystore
-rw-------. 1 185 root 3700 Aug 31 19:49 /opt/infinispan/server/conf/keystore.pkcs12
```

But the infinispan config file is only using the auto generated keystore 

```bash
sh-4.4$ cat /etc/config/infinispan.yaml
clusterName: tournamentcache
jgroups:
  transport: tcp
  dnsPing:
    query: tournamentcache-ping.petbattle.svc.cluster.local
  diagnostics: false
keystore:
  path: /opt/infinispan/server/conf/keystore
  password: password
  alias: server
  crtPath: /etc/encrypt
xsite:
  address: ""
  name: ""
  port: 0
  backups: []
logging:
  categories: {}
```

Which results in the following infinispan.xml in the conf directory
```bash
sh-4.4$ cat /opt/infinispan/server/conf/infinispan.xml
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 https://infinispan.org/schemas/infinispan-config-11.0.xsd
                            urn:infinispan:server:11.0 https://infinispan.org/schemas/infinispan-server-11.0.xsd
                            urn:org:jgroups https://www.jgroups.org/schema/jgroups-4.2.xsd"
        xmlns="urn:infinispan:config:11.0"
        xmlns:server="urn:infinispan:server:11.0">

.
.
.
        <security>
            <security-realms>
                <security-realm name="default">

                    <server-identities>
                        <ssl>
                            <keystore path="/opt/infinispan/server/conf/keystore" alias="server"
                                      keystore-password="password"
                                      generate-self-signed-certificate-host="localhost"/>
                        </ssl>
                    </server-identities>
.
.
                </security-realm>
            </security-realms>
        </security>

        <endpoints socket-binding="default" security-realm="default">
            <hotrod-connector name="hotrod">
                <authentication>
                    <sasl mechanisms="SCRAM-SHA-512 SCRAM-SHA-384 SCRAM-SHA-256 SCRAM-SHA-1 DIGEST-SHA-512 DIGEST-SHA-384 DIGEST-SHA-256 DIGEST-SHA DIGEST-MD5 PLAIN"
                          qop="auth" server-name="infinispan"/>
                </authentication>
            </hotrod-connector>
.
.
        </endpoints>
    </server>
</infinispan>
```

I think the problem is the keystore configuration in /etc/config/infinispan.yaml.
The keystore has a localhost self-signed cert where as the keystore.pkcs12 has the correct cert.
