### ISSUE TITLE
Remove secret intermediate yaml tree in authentication

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#62]
Initial authentication configuration is a little verbose, e.g.

```
  connector:
    authentication:
      secret:
        type: Credentials
        secretName: conn-auth-secret
```

`secret` should be removed for clearer configuration:

```
  connector:
    authentication:
      type: Credentials
      secretName: conn-auth-secret
```
