### ISSUE TITLE
Avoid empty xsite and other config fields if not defined and required

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#634]
infinispan.yaml in ConfigMap
```
clusterName: example-infinispan
jgroups:
  transport: tcp
  dnsPing:
    query: example-infinispan-ping.infinispan-operator.svc.cluster.local
  diagnostics: false
keystore:
  path: /opt/infinispan/server/conf/keystore
  password: password
  alias: server
  crtPath: /etc/encrypt
xsite:
  address: ""
  name: ""
  port: 0
  backups: []
logging:
  categories: {}
```

empty optional struct values such as `xsite` and `logging` should be omitted
