### ISSUE TITLE
Static xsite configuration should update host for local site

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#648]
In case of `expose.type` defined as `LoadBalancer` the host generates automatically and need to be defined on the next xsite instance. It would be nice to update it for local inside Infinispan CR. Example generated xsite configuration for AWS
In this case `host` for local location (sorry for tautology) doesn't make sense and can/must skipped
```
xsite:
  address: a54b11dfc5dec4182b5617730344ccd2-1857805667.eu-central-1.elb.amazonaws.com
  name: LON
  port: 7900
  backups:
  - address: infinispan-nyc.myhost.com
    name: NYC
    port: 7900
```

Original Infinispan CR 
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 3
  service:
    type: DataGrid
    sites:
      local:
        name: LON
        expose:
          type: LoadBalancer
      locations:
        - name: LON
          host: infinispan-lon.myhost.com
          port: 7900
        - name: NYC
          host: infinispan-nyc.myhost.com
          port: 7900
```
