### ISSUE TITLE
Able to setup XSite for different namespaces

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#702]
I don't know what is the limitation to have setup XSite sites with different namespaces just adding 'namespace` as optional parameter into the `InfinispanSiteLocationSpec` structure. It wold be flexible configuration as much as possible

Final proposal:
- add `namespace` and `clusterName` options to the `InfinispanSiteLocationSpec` struct
- if `InfinispanSiteLocationSpec.namespace` not defined, namespace is the same as current cluster namespace
- if `InfinispanSiteLocationSpec.clusterName` not defined, name is the same as current cluster name

**Comment by pruivo** [comment]
It makes sense to me, at least for demos / POC / testing.
It would be nice to have the cluster name (not sure if it is the correct name, but I mean the `metadata.name`)  as well.

**Comment by dmvolod** [comment]
> It would be nice to have the cluster name (not sure if it is the correct name, but I mean the `metadata.name`) as well.

@pruivo how we can utilize this name in Cross-Site setup?

**Comment by pruivo** [comment]
using your PR (https://github.com/infinispan/infinispan-operator/pull/706) as an example:

```
    sites:
      local:
        name: SiteB
        expose:
          type: None
      locations:
        - name: SiteA
          url: <openshift REST endoint>
          project-name: example-clustera
        - name: SiteB
          url: <openshift REST endoint>
          project-name: example-clusterb
```

The operator would query opensift to get the cross-site service IP.
