### ISSUE TITLE
Batch CR

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#746]
# Proposal
We should create a "Batch" CR that allows for multiple Infinispan resources to be created using Infinispan's [CLI batch mode](https://infinispan.org/docs/stable/titles/cli/cli.html#batch_operations). The batch script is then executed by as a one-off event with the CR marked as complete once the initial batch has been executed.

The advantage of this approach is that it allows for users to create multiple resource types, e.g. counters & counters, as well as allowing a batch of arbritrary admin actions to be automated. Furthermore, as the operator is leveraging the CLI's existing capabities, there is no need to write additional code to interact with the Infinispan server.

## Configuration
Users can provide a batch CLI in one of two ways (exclusive):

### Inline
Inline definition in the CR spec `spec.config`:
  - Multi-line yaml string containing batch contents
  - Suitable if no additional files are required

```yaml
apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: example-inline-batch
spec:
  cluster: example-infinispan
  config: |
    create cache --template=org.infinispan.DIST_SYNC mybatch
    put --cache=mybatch hello world
    put --cache=mybatch hola mundo
    disconnect
```

### Config Map
File(s) provided by a ConfigMap specified via `spec.configMap`.
```yaml
apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: example-cm-batch
spec:
  cluster: example-infinispan
  configMap: batch-config-map
```

ConfigMap key `batch` contains the batch file to execute, as well as any additional files required by the script.
 
Local Dir
```
example-batch
├── batch
└── pcache.xml
```

CLI Batch file
```
create cache --file=pcache.xml pcache
disconnect
```

`kubectl create configmap batch-config-map --from-file=example-batch`

## Implementation
A [k8s job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) can be used to launch the CLI with the user provided ConfigMap mounted to the underlying pod so that the batch file can be executed. On completion of the job, the Batch CRs status can be updated to `Completed|Failed`.
