### ISSUE TITLE
Container Autoscaling

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#749]
https://github.com/infinispan/infinispan-operator/issues/691 deprecates the Cache Service in favour of providing the DataGrid service as the default and removing this configuration option.

Currently only the cache-service provides memory-based autoscaling, however it relies on assumptions about the cache's storage and replication type to determine when pods schould be scaled. This approach is not possible with the `DataGrid` service as users are able to use arbritrary cache configurations. Instead, we should introduce "container level" autoscaling where the number of pods increases and decreases based upon the memory usage of the entire container exceeding the configured upper or lower bound of memory usage percentage respectively.

**Comment by dmvolod** [comment]
Can we use HPA for DataGrid case?
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by ryanemerson** [comment]
It appears so :slightly_smiling_face: 

https://docs.openshift.com/dedicated/4/nodes/pods/nodes-pods-autoscaling.html#nodes-pods-autoscaling-creating-memory_nodes-pods-autoscaling

**Comment by rigazilla** [comment]
Last time I tried to use the default HPA memory metrics I didn't get good results, mainly because of the java memory management.
Maybe we can tune GC or investigate if HPA can be integrated with custom memory metrics.

**Comment by dmvolod** [comment]
Yeah, HPA custom metrics should support, but need to be validated
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/custom-metrics-api.md

**Comment by rigazilla** [comment]
A good starting point to design HPA/operator integration could be CPU autoscaling (#274): standard CPU load metric should work quite well to control pods scaling.

**Comment by ryanemerson** [comment]
There's also the [Kubernetes Event-driven Autoscaling](https://keda.sh/) that has integrations with PostgreSQL and Redis.

**Comment by ryanemerson** [comment]
A problem with a generic container wide approach is that it does not take into account the requirements of different cache types. Replicated and Distributed caches have very different requirements when it comes to autoscaling, therefore it's necessary for any autoscaling to be configured based upon the use-cases of the Infinispan cluster.

# Cache Scaling Semantics
Here we define how different cache types affect scaling.

## Replicated Cache

|        | Vertical Scaling                            | Horizontal Scaling                                                                                                                   |
|--------|---------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|
| CPU    | Allows increased read and write performance | Allows increased read performance, but results in slower writes as each additional pod needs to be included in every write operation |
| Memory | Increases capacity for all pods             | Doesn't make sense as all pods store all entries, so increasing the number of pods does not increase the total memory available      |

## Distributed Cache

|        | Vertical Scaling                            | Horizontal Scaling                                                                              |
|--------|---------------------------------------------|-------------------------------------------------------------------------------------------------|
| CPU    | Allows increased read and write performance | Does not improve CPU performance as entries are always read from entry primary or backup owners |
| Memory | Increases memory capacity of the cluster    | Increases memory capacity of the cluster                                                        |


# Proposal
Implement automatic Horizontal Scaling and require users/admins to manually perform Vertical scaling by updating the Infinispan `spec.container` fields.

Automically scaling an existing cluster vertically is tricky as it can lead to the cluster becoming unavailable due to a lack of resources. Furtheremore, K8s does not provide a mechanism to vertically scale OOB.

## Implementation
Based upon the [HorizontalPodAutoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).

We extend the Infinispan CRD to define the [scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource).

The `HorizontalPodAutoscaler` controller will then increase/decrease the Infinispan CR `spec.replicas` field based upon the behaviour defined in the `HorizontalPodAutoscaler` CR.

Utilising the `autoscaling/v2beta2` api can define fine grained control of the scale up/down behaviour. For example, utilising a `stabilizationWindowSeconds` to prevent excessive scaling resulting in rebalancing adversely affecting performance.

Below is an example `HorizontalPodAutoscaler` definition with a custom `scaleUp` definition.
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-infinispan
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1 
    kind: Infinispan 
    name: example-infinispan
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: 500Mi
  behavior: 
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Max
```

## User Configuration
The user can define scaling via one of three means:

1. Infinispan CR spec
    - User defines the high-level scaling behaviour required
    - Operator automatically creates the `HorizontalPodAutoscaler`
    - Requires a new Infinispan CR version

```
spec:
  autoscale:
    minReplicas: 1
    maxReplicas: 10
    resource:
      - name: cpu
        type: AverageValue | Utilization | Value
        # One of the below fields must be defined depending on the configure type
        averageValue: 500Mi
        value: 500Mi
        averageUtilisation: 50%
      - name: memory
        type: AverageValue | Utilization | Value
        # One of the below fields must be defined depending on the configure type
        averageValue: 500m
        value: 500m
        averageUtilisation: 50%
```

2. kubectl
    - `kubectl autoscale infinispan example-infinispan --cpu-percent=50 --min=1 --max=10`

3. Manually create `HorizontalPodAutoscaler`
    - Allows for more advanced configurations where the operator defaults are not appropriate
