### ISSUE TITLE
Use xsite://host:port URI configuration for static cross-site config

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#762]
We should remove separate `host` and `port` fields inside `spec.service.sites.locations` and use `xsite://host:port` URI for the `url` field. This will be aligned code with original design v3 described in #108 that's we missed during #604 implementation and code review. 

Current cross-site configuration
``` 
locations:
      - name: SiteA
        host: infinispan-sitea.myhost.com
        port: 7900
      - name: SiteB
        host: infinispan-siteb.myhost.com
        port: 7900
```
Planned cross-site configuration
``` 
locations:
      - name: SiteA
        url: xsite://infinispan-sitea.myhost.com:7900
      - name: SiteB
        url: xsite://infinispan-siteb.myhost.com:7900
```
This is much simple and flexible explicit configuration and we have a chance to fix this quickly before release.
