### ISSUE TITLE
Infinispan cluster shutdown/restart problem

### ISSUE THREAD

**Issue by mirostary** [infinispan/infinispan-operator#763]
Hello, 
I’m trying to restart the Infinispan cluster on OCP4.6. Basically, I apply this YAML:

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: a-tests-infinispan-cluster
  namespace: datagrid-cluster
spec:
  replicas: 2
  service:
    type: DataGrid
  container:
    storage: 2Gi
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "2000m"
    memory: 1Gi
  security:
    endpointSecretName: connect-secret
    endpointEncryption:
      type: Secret
      certSecretName: tls-secret
  expose:
    type: LoadBalancer
```

Then I change the number of replicas to 0 and apply again. And here is the problem, sometimes the cluster got the “stopping” condition (just stop the pods), and sometimes it got the “gracefulShutdown” condition (terminate the pods)… I wasn’t able to find out why I got a different condition when I didn't change anything.

I tried changing the `.spec.container` settings but without success. I wasn’t able to find out the reason in the guide... Do you know where is the problem?

I have installed the Datagrid operator 8.1.3 in another namespace and it is watching the namespace "datagrid-cluster".
The Openshift version is 4.6.9

**Comment by dmvolod** [comment]
Test sometimes hangs with following status, i.e. `Stopping` condition has not been cleared in some cases, however `WellFormed` condition is set to `True`
```
  status:
    conditions:
    - status: "True"
      type: PreliminaryChecksPassed
    - message: 'View: test-check-data-survive-to-shutdown-0-2251'
      status: "True"
      type: WellFormed
    - status: "True"
      type: Stopping
    consoleUrl: http://172.18.0.2:32041/console
    podStatus:
      ready:
      - test-check-data-survive-to-shutdown-1
    statefulSetName: test-check-data-survive-to-shutdown
```
