### ISSUE TITLE
Allow client certificate authentication

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#851]
It should be possible for a user to provide a truststore via the `tls-secret` and configure whether client cert validation or authentication should be enabled.

```yaml
spec:
  security:
    endpointEncryption: 
            type: Secret 
            certSecretName: tls-secret 
            clientCert: None | Validate | Authenticate
```

A user secret would then be as follows:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: Opaque
stringData:
    alias: server 
    password: password 
data:
    keystore.p12:  "MIIKDgIBAzCCCdQGCSqGSIb3DQEHA..." 
    truststore.p12: "MIIKDgIBAzCCCdQGCSqGSIb3DQEHA..." 
```

N.B. With this proposal truststores can't be configured with `spec.security.endpointEncryption.type = Service`

### Validate
Only a truststore is created:

```xml
         <server-identities>
            <ssl>
               <keystore path="server.pfx" relative-to="infinispan.server.config.path" keystore-password="secret"
                         alias="server"/>
               <truststore path="ca.pfx"  relative-to="infinispan.server.config.path" password="secret"/>
            </ssl>
         </server-identities>
```

### Authenticate
Both a truststore and a trustore-realm is created.

```xml
   <security-realms>
      <security-realm name="default">
         <server-identities>
            <ssl>
               <keystore path="server.pfx" relative-to="infinispan.server.config.path" keystore-password="secret"
                         alias="server"/>
               <truststore path="trust.pfx"  relative-to="infinispan.server.config.path" password="secret"/>
            </ssl>
         </server-identities>
         <truststore-realm/>
      </security-realm>
   </security-realms>
```

# Operator 2.0.x
Only `clientCert: None | Authenticate` can be supported as truststore-realms are mandatory so Validate is not possible.
