### ISSUE TITLE
CRD views load indefinitely on OpenShift

### ISSUE THREAD

**Issue by Crumby** [infinispan/infinispan-operator#874]
**Operator version:** 2.1.2
**OpenShift version:** 4.7.0

Any CRD (Backup, Caches, Infinispan, Restore) view in OpenShift console loads indefinitely. All of those CRD have common "Violation" status set to True:

```
conditions:
  - lastTransitionTime: "2021-03-04T16:29:57Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```
