### ISSUE TITLE
Unable to connect console on OCP with default endpoint encryption and Firefox browser

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#888]
At least minimal Infinispan CR configuration with Route exposition on OCP and Infinispan server 12.0.1 cause error (attached Pod logs)
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 2
  expose:
    type: Route
```
[infinispan-pod.log](https://github.com/infinispan/infinispan-operator/files/6114653/infinispan-pod.log)
