### ISSUE TITLE
Batch CR remains an orphan if configured with explicit ConfigMap option

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#906]
After Infinispan CR deletion following Batch CR remains an orphan
```
apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: my-batch
spec:
  cluster: example-infinispan
  configMap: batch-config-map
```

`controllerutil.SetControllerReference(infinispan, batch, r.scheme)` calls if `spec.ConfigMap == nil` otherwise the owner reference is not set
