### ISSUE TITLE
Application and admin refer to same secret

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#92]
```
spec:
  containers:
  - env:
    - name: ADMIN_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: connect-secret
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: connect-secret
    - name: APPLICATION_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: connect-secret
    - name: APPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: connect-secret
```

Admin username/password should be referencing `mgmt-secret`
