### ISSUE TITLE
xsite setup error: no matches for kind "Service" in version "v1"

### ISSUE THREAD

**Issue by K890** [infinispan/infinispan-operator#928]
I am trying to configure xsite using a bare metal k8s cluster and an EKS instance using the guide: https://infinispan.org/infinispan-operator/master/operator.html#backup_sites
. Both the servers are running on v1.19

I installed the infinispan operator using the commands below on both the k8s clusters:
```
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0
kubectl create -f https://operatorhub.io/install/infinispan.yaml
```

Here is the spec for site-1:
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: nightly-infinispan
spec:
  replicas: 2
  container:
    extraJvmOpts: "-Dinfinispan.bind.address=0.0.0.0"
  service:
    type: DataGrid
    sites:
      local:
        name: k8s-blue
        expose:
          type: NodePort
      locations:
      - name: k8s-blue
        url: kubernetes://x.x.x.x:6443
        secretName: k8s-blue-token
      - name: eks-server
        url: kubernetes://<dns-alphabets>.yl4.us-east-x.eks.amazonaws.com:443
        secretName: eks-server-token
  logging:
    categories:
      org.infinispan: debug
      org.jgroups: debug
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error

```
Here is the spec for site-2:

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: nightly-infinispan
spec:
  replicas: 2
  container:
    extraJvmOpts: "-Dinfinispan.bind.address=0.0.0.0"
  service:
    type: DataGrid
    sites:
      local:
        name: eks-server
        expose:
          type: NodePort
      locations:
      - name: k8s-blue
        url: kubernetes://x.x.x.x:6443
        secretName: k8s-blue-token
      - name: eks-server
        url: kubernetes://<dns-alphabets>.yl4.us-east-x.eks.amazonaws.com:443
        secretName: eks-server-token
  logging:
    categories:
      org.infinispan: debug
      org.jgroups: debug
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error

```

When these specs are applied on the respective clusters, I am seeing the below error on the infinispan-operator pod:

```
{"level":"error","ts":1616398925.5081518,"logger":"config-controller","msg":"Error in computeXSite configuration","Reconciling":"ConfigMap","Request.Namespace":"nightly-infinispan","Request.Name":"nightly-infinispan","error":"no matches for kind \"Service\" in version \"v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/infinispan/infinispan-operator/pkg/controller/infinispan/resources/config.(*configResource).Process\n\t/infinispan-operator/pkg/controller/infinispan/resources/config/config_controller.go:89\ngithub.com/infinispan/infinispan-operator/pkg/controller/infinispan/resources.(*Controller).Reconcile\n\t/infinispan-operator/pkg/controller/infinispan/resources/resource_controller.go:150\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

According to https://kubernetes.io/docs/concepts/services-networking/service/, the kind `Service` does belong to the api version `v1`. 

Either I am missing something or the error is misleading.
