### ISSUE TITLE
Reconcile loop can hangs if setup LoadBalancer expose type not supported for the hosting platform

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#940]
If hosting platform, for example Kubernetes or OCP/OKD on bare-metal not supported or not configured with LoadBalancer, the following Infinspan CR configuration can hangs within the reconcile loop
```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 2
  expose:
    type: LoadBalancer
```
This is limitation and regression of the #730
