### ISSUE TITLE
Services Spec.Ports should be fully specified to avoid additional updates from k8s controller

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#954]
It's possible to omit some optional parameters of the Service, i.e. `Protocol` and `Port` which are not required, but this will cause additional Services update form the k8s service controller and will cause additional reconcile call in our controllers watching the services 

```
spec:
  ports:
    - name: infinispan
      protocol: TCP
      port: 11222
      targetPort: 11222
    - name: infinispan-adm
      protocol: TCP
      port: 11223
      targetPort: 11223
```
