### ISSUE TITLE
Automatically Create Cluster ServiceMonitor

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#959]
A simple solution is to create the ServiceMonitor in the same namespace as the Infinispan CR and it's up to the user to configure their Prometheus `serviceMonitorNamespaceSelector` so that the required namespaces are scanned. In the case of openshift, no additional configuration is required if user workload monitoring is utilised.

**Comment by dmvolod** [comment]
We should implement creation of the `ServiceMonitor` and corresponding `Secret` as an option based on
- specific `infinispan.org/monitoring: "true"` annotation in the Infinispan CR
- global `infinispan.service.monitoring.enable: true` inside `infinispan-operator-config` ConfigMap.

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
  annotations:
    infinispan.org/monitoring: "true"
spec:
  replicas: 1
```

The single limitation, if user will change global option from `false (absence)` to `true` and vise versa, old Infinispan CR's will never handled and ServiceMonitor CR's  will never created or deleted, until operator restart (every controller will reconcile once for every CR on startup).
In this case we should send SIGTERM in the operator internally if `configcontroller` detects that global monitoring option has changed to restart operator and start global reconcilation
