### ISSUE TITLE
Infinispan Cloud Event integration must be configurable by the user

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-operator#962]
The user must be allowed to configure Cloud Event integration in the infinispan configuration.

A suitable solution could be:
- add in the infinispan CR a cloudEvent field as follow:
```
cloudevent:
  bootstrap-servers: 
  acks:
  cache-entries-topic:
```
- propagate it to the config-generator that will add the following xml fragment in the infinispan.xml:
```
 <cloudevents bootstrap-servers="127.0.0.1:9092" acks="0" cache-entries-topic="cache-events"/>
 ```
